<?php

return [
    'name' => env('RESTAURANT_NAME', 'Your Restaurant'),
    'tagline' => env('RESTAURANT_TAGLINE', 'Fresh food, warm service'),
    'hero_badge' => env('RESTAURANT_HERO_BADGE', 'Open today'),
    'hero_title' => env('RESTAURANT_HERO_TITLE', 'Fresh dishes,'),
    'hero_accent' => env('RESTAURANT_HERO_ACCENT', 'cooked to order.'),
    'hero_subtitle' => env('RESTAURANT_HERO_SUBTITLE', 'Browse the live menu, reserve a table, or order for pickup and delivery. Every dish is prepared in our kitchen from current stock.'),
    'phone' => env('RESTAURANT_PHONE', '+880 1700-000000'),
    'email' => env('RESTAURANT_EMAIL', 'hello@restaurant.test'),
    'address' => env('RESTAURANT_ADDRESS', 'Your restaurant address'),
    'guest_rating' => '4.8',
    'hours' => [
        ['label' => 'Sat – Thu', 'time' => '11:00 AM – 11:00 PM'],
        ['label' => 'Friday', 'time' => '3:00 PM – 11:00 PM'],
    ],
    'about' => [
        'title' => 'A neighbourhood kitchen built around honest cooking.',
        'text' => 'We cook from a live menu, keep stock honest, and serve guests who want a calm meal — dine in, pick up, or order online.',
        'points' => [
            ['title' => 'Live kitchen menu', 'text' => 'Dishes stay on the board only while ingredients last.'],
            ['title' => 'Table or takeaway', 'text' => 'Reserve a seat, collect from the counter, or order delivery.'],
            ['title' => 'Tracked from fire to table', 'text' => 'Every order moves through the kitchen so guests always know the status.'],
        ],
    ],
    'content' => [
        'footer_blurb' => 'Dine in, order online, or book a table. The kitchen cooks from today’s stock so the menu you see is the menu we can serve.',
        'footer_note' => 'Live menu, kitchen display, reservations, and guest ordering.',
        'cta_title' => 'Book a table, or send an order to the kitchen.',
        'features_label' => 'Restaurant system',
        'features_title' => 'Dining the way a real kitchen works',
        'features_intro' => 'Guests see a live menu, place orders, reserve tables, and follow the kitchen — all from one restaurant management system.',
        'features' => [
            ['title' => 'Live menu', 'text' => 'Browse today’s dishes with photos, prices, and remaining servings. Out-of-stock items are marked before you order.'],
            ['title' => 'Online ordering', 'text' => 'Add dishes to your cart, choose cash on delivery, and track the order from pending to delivered.'],
            ['title' => 'Table reservations', 'text' => 'Pick a date, time slot, and party size. The floor team confirms the booking from the console.'],
            ['title' => 'Kitchen-ready stock', 'text' => 'Recipes map to inventory. When a dish starts cooking, stock is deducted so the next guest sees the truth.'],
        ],
        'process_label' => 'Guest journey',
        'process_title' => 'From menu to plate',
        'process' => [
            ['step' => '01', 'title' => 'Browse', 'text' => 'Open the live menu. Photos preview in a dish card. Sold-out items are marked.'],
            ['step' => '02', 'title' => 'Order or reserve', 'text' => 'Add to cart for pickup or delivery, or book a table for dine-in.'],
            ['step' => '03', 'title' => 'Kitchen cooks', 'text' => 'Staff approve, chefs cook, and status steps turn green as the ticket moves.'],
            ['step' => '04', 'title' => 'Enjoy', 'text' => 'Collect, dine in, or follow delivery. Cancel while the kitchen has not started.'],
        ],
        'hero_tiles' => [
            ['title' => 'Live order tracking', 'text' => 'Follow your ticket from pending to delivered with the same statuses the kitchen uses.'],
            ['title' => 'Stock-aware dishes', 'text' => 'If a recipe runs out, the dish leaves the board. No ghost items.'],
            ['title' => 'Table booking online', 'text' => 'Choose date, slot, and party size. The restaurant confirms from the floor console.'],
        ],
        'featured_label' => 'Tonight’s board',
        'featured_title' => 'Featured dishes',
        'menu_label' => 'What we serve',
        'menu_title' => 'Live kitchen menu',
        'menu_intro' => 'Explore today’s dishes. Tap a dish to preview, then add it to your cart. Servings stay visible from current stock.',
        'about_label' => 'Our story',
        'about_points' => [
            ['title' => 'Live kitchen menu', 'text' => 'Dishes stay on the board only while ingredients last.'],
            ['title' => 'Table or takeaway', 'text' => 'Reserve a seat, collect from the counter, or order delivery.'],
            ['title' => 'Tracked from fire to table', 'text' => 'Every order moves through the kitchen so guests always know the status.'],
        ],
        'about_paragraphs' => [
            'Our kitchen is built around simple preparation, dependable service, and food that feels fresh from the first plate to the last. Guests can enjoy a calm dine-in experience, place an order for pickup, or choose delivery when they want the same care at home.',
            'Every part of the service is handled with attention: ingredients are checked before prep, orders are tracked through the kitchen display, and the team keeps the dining room warm, clean, and welcoming throughout the day.',
        ],
        'contact_label' => 'Contact us',
        'contact_title' => 'Location & hours',
        'contact_intro' => 'Dine in, pick up, or order delivery. Reserve a table online — no phone call needed.',
        'reserve_label' => 'Book a table',
        'reserve_title' => 'Online reservation',
        'reserve_intro' => 'Choose a date, time slot, and party size. We will confirm your booking from the floor console.',
        'login_title' => 'Your table, your order, one account.',
        'login_subtitle' => 'Sign in to order from the live menu, track kitchen status, and manage reservations.',
        'register_title' => 'Create a guest account',
        'register_subtitle' => 'Register to place orders, follow kitchen status, and manage your table bookings.',
        'staff_login_title' => 'Kitchen, floor and stock in one console.',
        'staff_login_subtitle' => 'Sign in to manage orders, reservations, inventory alerts, and the kitchen display.',
        'dashboard_kicker' => 'Operations',
        'guest_stat_label' => 'Guest rating',
        'kitchen_stat_label' => 'Kitchen synced',
        'refund_title' => 'Cancellation & refund policy',
        'refund_items' => [
            ['title' => 'Pending', 'text' => 'Cancel anytime. Cash on delivery orders are not charged.'],
            ['title' => 'Approved', 'text' => 'Cancel until cooking starts. Paid orders receive a full refund.'],
            ['title' => 'Preparing / Ready', 'text' => 'Cancellation is closed once the kitchen starts your order.'],
            ['title' => 'Delivered', 'text' => 'No refund after the order is delivered.'],
        ],
    ],
    'images' => [
        'icon' => 'images/brand/restaurant-icon.svg',
        'hero' => 'images/brand/hero.jpg',
        'about' => 'images/brand/about.jpg',
        'login' => 'images/brand/login.jpg',
        'staff' => 'images/brand/staff.jpg',
        'contact' => 'images/brand/contact.jpg',
        'dish_fallback' => 'images/dishes/plain-rice.jpg',
    ],
];
